version: "3"
services:
  db:
    env_file: ./build/env/development/db.env
    image: postgres
    volumes:
     - postgres:/var/lib/postgresql/data

  api:
    env_file: ./build/env/development/api.env
    build: .
    command: ./rtc
    ports:
      - 8888:8888
    volumes:
      - .:/app
    depends_on:
     - db

volumes:
  postgres: