# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.13
        environment:
          GO111MODULE: "on"
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    environment:
      WORKDIR: /go/src/github.com/sebach1/git-crud 
    working_directory: $WORKDIR

    steps:
      - checkout
      - run:
          name: "install external software deps"
          command: |
            sudo apt-get install build-essential
            git clone git@github.com:google/jsonnet.git ~/jsonnet
            cd ~/jsonnet
            make
            sudo mv ./jsonnet* /usr/bin
            cd $WORKDIR
      - run:
          name: "install internal project deps & run tests"
          command: |
            go get -v -t -d ./...
            go test -v --race ./...